#!/usr/bin/env bash
# SSH client configuration

Host *
	PasswordAuthentication no
	IdentityFile ~/.ssh/mykey
	SendEnv LANG LC_*
	HashKnownHosts yes
	GSSAPIAunthentication yes
	GSSAPIDelegateCredentials no
